#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           LD,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RD,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author		Sean Kelley      sgtkode01@gmail.com
 * @author		Bernard Suwirjo  bsuwirjo@gmail.com
 * @author 		Spencer Couture  spence.couture@gmail.com
 * @author		Kyle Moran			 kyle@llamachair.com
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// all functions for competition code
#include "functions.c"



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton(){
	bStopTasksBetweenModes = true;

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */
task autonomous(){
	turnRightDegrees(90, 100);
}




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when driver controls the bot
 */
task usercontrol(){
	startTask(userControlls);
	bool isIntakeOn = false;
	bool isLauncherOn = false;

  while (true)
	{
    if(bVEXNETActive){
			/////////////////////////////////////////////////////////////////////////////////////////
			//
			//                                      Drive
			//
			/////////////////////////////////////////////////////////////////////////////////////////

			//The following two lines allow the driver to controll the robot
			motor[RD] = vexRT[Ch2];
			motor[LD] = vexRT[Ch3];


			if(vexRT[Btn7D] == 1){	//if button 7D is pressed toggle launcher (On / Off )
				if(isLauncherOn){
					motor[LL] = 0;
					motor[LR] = 0;
					isLauncherOn = false;
				}else{
					motor[LL] = 80;
					motor[LR] = 80;
					isLauncherOn = true;
				}
			}

			if(vexRT[Btn8D] == 1){	//if button 8D is pressed toggle intake  ( On / Off)
				if(isIntakeOn){
					motor[intake] = 0;
					isIntakeOn = false;
				}else{
					motor[intake] = 80;
					isIntakeOn = true;
				}
			}

      wait1Msec(10);
    }
	}
}
